### ISSUE TITLE
V0.13 not running on Arduino Mega 2560 anymore

### ISSUE THREAD

**Issue by tmsidrg** [BleuLlama/TinyBasicPlus#2]
Last tested V.0.02a - it was running on Arduino Uno and on Arduino Mega 2560.
Now V 0.13 is running fine on Arduino Uno (much more RAM and great EEPROM storage) but is not running on Mega 2560 anymore. Pin13LED is blinking all the time (blink-blink-pause blink-blink-pause ...) but nothing on the serial console. Used pure Arduino Mega 2560 (no shields) and sketch was unchanged as downloaded.

**Comment by BleuLlama** [comment]
(Noted in the latest soon-to-be-checked-in source). closing

**Comment by TylerOfftimeBrown** [comment]
2781 for Chinese mega pro
TinyBasic Plus v0.15
5818 bytes free.
4096 EEProm bytes total.
