### ISSUE TITLE
Stuck on "HELLO TinyBasic Plus v0.13" on Leonardo

### ISSUE THREAD

**Issue by m0ric3** [BleuLlama/TinyBasicPlus#3]
Tiny BASIC used to run great on my Leonardo, howevever I could never get the DREAD or AREAD commands to work, so I looked I tried typing AREAD( A, 13 ) and I had a crash and ever since I try re-uploading the code, the serial monitor gets stuck in the "HELLO TinyBasic Plus v0.13" message, it wont take any command or even gibberish, whatever I send doenst even show up in the monitor. I've tried re-downloading and using different Serial communication softwares and nothing seems to help.

**Comment by BleuLlama** [comment]
Weird.  Not sure why that happened.  Thank you for tracking it down.

Closing this ticket, and created a new ticket, #43 to look into why this happened,
