### ISSUE TITLE
The input command has no documentation and I can not get it to work

### ISSUE THREAD

**Issue by pcmr106** [BleuLlama/TinyBasicPlus#30]
I have been working on this for about an hour now, I would like to know how to use the input command

**Comment by BleuLlama** [comment]
As mentioned in the docs the INPUT command is currently nonfunctional

**Comment by BleuLlama** [comment]
Hi. Not sure if you're still interested in this, but INPUT is implemented now. (it might have been in the past as well.)  But as you mention; no documentation.

I have documented it on the main page.  In short:  10 INPUT A    - will take input from the user, and store it in variable A.  It will accept numbers/expressions.  So you can use integers "43", "88" or variable names "a"   etc But not textual strings.

**Comment by pcmr106** [comment]
Thanks, I'll have to try it out now
