### ISSUE TITLE
Why I can't use DREAD,AREAD?

### ISSUE THREAD

**Issue by RESBI** [BleuLlama/TinyBasicPlus#32]
>DREAD
What?
>AREAD
What?

What???

**Comment by BleuLlama** [comment]
You need to use proper syntax for them.  You're not specifying where it should read from, also, DREAD/AREAD are functions and need to be called as such.

Some examples of the proper format:

10 A = DREAD( 3 )
20 B = AREAD( 2 )
30 DWRITE 4, HIGH 
40 AWRITE 6, 128

**Comment by RESBI** [comment]
Thank you!
