### ISSUE TITLE
Integer constants silently overflow while parsing.

### ISSUE THREAD

**Issue by drawkula** [BleuLlama/TinyBasicPlus#37]
[Integer constants silently overflow while parsing](https://github.com/BleuLlama/TinyBasicPlus/blob/083bba9237770f05b3971f2ff5b1a2a51dcd5530/Arduino/TinyBasicPlus.ino#L746-L767).

Example run on Debian9/AMD64:
```
$ ./tbp 
Starting up TinyBasic Plus...

65362 bytes free.
OK
>print 32768
print 32768
-32768
>print -32769
print -32769
32767
```
The overflow happens on Arduini too.

**Comment by BleuLlama** [comment]
Numbers are stored as a 2 byte signed number.  This is how Tiny Basic was implemented, and is fairly standard for some BASIC variants.

Sorry if this doesn't suit your needs, but hey, limitations are fun to work around, right?  :)

I'm going to close this one as "as designed."
