### ISSUE TITLE
PLEASE ADD INPUT COMMAND FOR USER INPUT

### ISSUE THREAD

**Issue by Bopstar** [BleuLlama/TinyBasicPlus#38]
I would love someone to add the input command so a programme can ask for a user input weather its a name or a variable e.g. Pick a number between 1 and 10. this would make programmes so much more us full /functional.

Kind regards,
Justin Harris

**Comment by BleuLlama** [comment]
The INPUT is available.  I added some documentation about it on the main page.  It only accepts expressions though. not text strings.  So you can enter an immediate number or variable name, etc.
